# Generated by Django 3.1.1 on 2020-10-01 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201001_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='Name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='Clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.clinic'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='LastRegister',
            field=models.DateTimeField(),
        ),
    ]
