# Generated by Django 3.1.1 on 2020-10-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201001_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='LocalIp',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanner',
            name='RemoteIp',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
