# Generated by Django 3.1.1 on 2020-10-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201002_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='HWmodel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scanner',
            name='SWversion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
