# Generated by Django 3.1.1 on 2020-10-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20201002_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='Charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='LastRegister',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
