# Generated by Django 3.1.1 on 2020-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20201019_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='HWmodel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='SWversion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
